### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ellieeet123** [John2212ho/john2212ho.github.io#1]
Hi there. I was wondering if you would mind giving me credit for making this website. I saw that on the homepage it states that the website was created by a guy named Samir.
![image](https://user-images.githubusercontent.com/75391956/156664692-4a0490df-3830-4e90-9d24-bacb4c305970.png)
![image](https://user-images.githubusercontent.com/75391956/156664429-c0506b38-f037-4139-86ce-8d9ec144d4ca.png)
However for the most part, this website was created by me, and I was wondering if you wouldn't mind just acknowledging that. Thanks.

**Comment by John2212ho** [comment]
ok
